[package]
name = "varray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
parking_lot = "*"
region = "3"

[[bench]]
name="bench"
path="src/bench.rs"